version: 0.1

phases:
  build:
    commands:
#SONAR QUB
      - mvn verify sonar:sonar -Dsonar.projectKey=ervishnu -Dsonar.organization=ervishnu -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$Sonar_Token
#QUALITY GATE
      - sleep 5
      - |- 
        quality_status=$(curl -s -u f3b08cc818665492dc37188ca47d238ae4204e9a: https://sonarcloud.io/api/qualitygates/project_status?projectKey=ervishnu | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
#        if [ $quality_status = "ERROR" ] ; then exit 1;fi
#MVN Build
      - sleep 5
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
      - '**/*'