#!/bin/bash

set -e

# Install Java if not yet installed
{ which java; } || { yum install -y java; }

# Download the latest Tomcat9 version
rm -rf /tomcat
mkdir /tomcat
cd /tomcat
{ which wget; } || { yum install -y wget; }
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz

# Install tomcat if not yet installed
tar -xzvf apache-tomcat-9.0.80.tar.gz

./apache-tomcat-9.0.80/bin/startup.sh